### ISSUE TITLE
Tooltip component to display content more than one line in new line (to display filed value in line by line)

### ISSUE THREAD

**Issue by YogeshPatelGoa** [GovAlta/ui-components#1523] opened 2023-12-13 17:45 UTC
## Acceptance Criteria:

![image](https://github.com/GovAlta/ui-components/assets/124069025/4bff2497-2d2b-4a49-8bf0-b0c8aa65cf8b)

![image](https://github.com/GovAlta/ui-components/assets/124069025/fd53c4f5-d795-4b35-9ef9-ee7233562734)

**Comment by ArakTaiRoth** [comment] 2023-12-13 21:01
Closing, duplicate of #1524

**Closed by ArakTaiRoth** 2023-12-13 21:01 UTC
