### ISSUE TITLE
GoAInputText element from GoA storybook is not supporting the if condition

### ISSUE THREAD

**Issue by Akhilgsd** [GovAlta/ui-components#1082] opened 2023-03-31 16:19 UTC
If you need help putting your report together
Get in touch with the design system team on Slack at [#design-system-support](https://goa-dio.slack.com/archives/C02PLLT9HQ9)

### Describe the bug

Pasting the code with GoAInputText and my own element InputText element. if condition is not working in the GOA element

        {/* <input
            value={formData['health-number']}
            onChange={(e) => {
              if (e.target.value.length <= 12) {
                setFormData({ ...formData, 'health-number': e.target.value });
              }
            }}
          /> */}

        <GoAInputText
          width="60ch"
          name="health-number"
          value={formData['health-number']}
          onChange={(name, value) => {
            if (value.length <= 12) {
              setFormData({ ...formData, 'health-number': value });
            }
          }}
        />

### What is the level of criticality

they are many repeated fields so i use this every day.  highly priority.

### Expected behavior

GoaInputText element should accept the condition

**Comment by ArakTaiRoth** [comment] 2023-03-31 17:54
@Akhilgsd Can you share more of the code, how you have `formData` and `setFormData` setup? I attempted this with a slightly simpler solution
```
<GoAInputText
        width="60ch"
        name="health-number"
        value={textValue}
        onChange={(name, value) => {
          if (value.length <= 12) {
            setTextValue(value);
            console.log(textValue);
          }
        }}
      />
```
And it works fine, so I don't see a problem with if statements. There shouldn't be any issues with any functionality passed into the `onChange` function, as we do nothing with it, it's just passed through to be run as it is.

**Comment by Akhilgsd** [comment] 2023-03-31 20:11
![image](https://user-images.githubusercontent.com/122409529/229220100-a41b7f02-35c1-480c-abea-e13e418abd81.png)

I tried same but, no chnage 

  const [healthNumber, setHealthNumber] = useState(formData['health-number']);
 <GoAInputText
          width="60ch"
          name="health-number"
          value={healthNumber}
          onChange={(name, value) => {
            if (value.length <= 12) {
              setHealthNumber(value);
              setFormData({ ...formData, 'health-number': value });
            }
          }}
        />

**Comment by ArakTaiRoth** [comment] 2023-03-31 21:29
@Akhilgsd In your code that you sent saying you tried the same, you're still using `setFormData` instead of the expected `setHealthNumber`.

**Comment by ArakTaiRoth** [comment] 2023-03-31 21:31
@Akhilgsd Just wondering, are you getting any errors in the console from this? You're still using the code `setFormData`, I'm wondering if there's a problem in that that's causing errors.

If you can, share your repo and branch, and I can always take a closer look. But from my initial testing with just a simple use case, everything works as intended.

**Comment by Akhilgsd** [comment] 2023-04-03 02:50
My apologies for late response. please have look on my branch.
repo- https://github.com/GovAlta/mcod.
branch- MCOD-239/NEW
location- apps/mcod-webapp/apps/mcod-react/src/Components/mcod-registration/mcod-registration-steps/McodRegistrationStep1.tsx.

Please take a look.

**Comment by ArakTaiRoth** [comment] 2023-04-04 22:33
@Akhilgsd A couple things. I was unable to run this to actually test it. It took 25 minutes to build the image, and even after building it, running it didn't seem to work. But here's a couple things to check on initial glance:
1. In your `package.json`, you have `react-components` in your `devDependencies`, it should probably be included in your `dependencies` where `web-components` is located.
2. I notice you're using if statements in other GoAInputText elements, are those also giving you problems? Specifically lines 459, a ternary on line 390, lines 345, and 327.
3. Are you getting any errors when testing this particular if statement?

**Comment by chrisolsen** [comment] 2023-04-05 04:07
The reason this is happening is because the component value is being set internally whenever the input is changed. The setting of the value might be able to be removed but it works have to be thoroughly tested before taking the chance to make sure it cause no basis in other projects.

**Comment by Akhilgsd** [comment] 2023-04-05 13:46
Thank you, team. I will take a look.

**Comment by ArakTaiRoth** [comment] 2023-04-05 23:51
@Akhilgsd Let me know if there are any other issues, if not, I will be closing this issue on EoD Friday.

**Comment by Akhilgsd** [comment] 2023-04-11 14:48
Hello Team,
I tried in all possible ways, but unable to fix this issue. Could anyone connect on team? i can explain the situation.

**Comment by ArakTaiRoth** [comment] 2023-04-11 17:58
@Akhilgsd I can be available after 1pm MST on Teams.

**Comment by ArakTaiRoth** [comment] 2023-06-12 17:44
@Akhilgsd Closing this issue, as it's been 2 months now and no one has reached out to elaborate on the issue. If this is still an issue, please reach out to me on Slack.

**Closed by ArakTaiRoth** 2023-06-12 17:44 UTC
Labels: Bug
