### ISSUE TITLE
Checkbox: Add margin to bottom of description

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#1771] opened 2024-04-11 16:54 UTC
## Acceptance Criteria:

- Add `--goa-space-m` margin to the bottom of the checkbox description when the property is enabled
- This additional spacing should not be there when the checkbox description is hidden

## Background:
This issue is in response to the issue reported by bug #1519. This fix will not elevate this issue but working on this issue made apparent this spacing issue present with the checkbox component.

**Comment by bdfranck** [comment] 2024-04-15 21:50
I also noticed this issue when I was working on my [PR](https://github.com/GovAlta/ui-components/pull/1777) to fix https://github.com/GovAlta/ui-components/issues/1768. The issue is that we add spacing by putting a fixed [minimum height](https://github.com/GovAlta/ui-components/pull/1777/files/bbe3412658d4896edc3e3cfd9d0e2576cdc41024#r1563189413) on the checkbox instead of bottom padding.

In my [PR](https://github.com/GovAlta/ui-components/pull/1777), I remove the minimum height and use bottom padding instead.

![image](https://github.com/GovAlta/ui-components/assets/1479091/a840e9b8-776a-4ccf-8d77-d4655fea805c)

![image](https://github.com/GovAlta/ui-components/assets/1479091/417f2998-652e-4e9f-bde3-1c444684338a)

This is the same approach that we have for radio buttons.
![image](https://github.com/GovAlta/ui-components/assets/1479091/a314b4ca-d5ea-4bbd-8093-bc23b4101868)

@Spark450 Does this solve the issue? Are there any other situations that I should be considering?

**Comment by twjeffery** [comment] 2024-05-23 00:05
@bdfranck This looks fixed to me! Awesome! Is this one good to close then?

**Comment by bdfranck** [comment] 2024-05-23 14:25
@twjeffery Odd. I ended up removing the bottom margin from my PR because I thought it was already fixed. 
https://github.com/GovAlta/ui-components/pull/1777#discussion_r1563189413

I checked in `alpha` and we're still using a min height instead of a bottom margin on the checkbox.
<img width="768" alt="image" src="https://github.com/GovAlta/ui-components/assets/1479091/9a8a062b-3929-454a-9ac9-aff4288c42f9">

We should keep this issue open until it's resolved.

**Closed** 2024-06-04 16:46 UTC
Labels: Bug, ready-for-contribution
